routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::domain('store.zineta.test')->group(function () {
    Route::resource('category','CategoryController');
    Route::resource('product','ProductController');
    Route::get('/store','ProductController@home');
    Route::get('product/{id}/view','ProductController@detail')->name('product.detail');
    Route::view('/coba', 'front_end.store.product-view');
    Route::view('/','lookbook_');
    Route::post('addtocart/{id}','TransactionController@addToCart')->name('addtocart');
    Route::get('cart','TransactionController@cart')->name('cart');
    // Route::get('cartNew','TransactionController@cartNew')->name('cartNew');
    Route::POST('checkout','TransactionController@checkout');
    Route::get('shipment','TransactionController@shipment');
    Route::get('payment/{id}','TransactionController@payment');
    Route::put('cancelpayment/{id}','TransactionController@cancelPayment');
    Route::get('mytransaction','TransactionController@myTransaction')->name('mytransaction');
    Route::get('transaction','TransactionController@index');
    Route::get('transaction/{id}','TransactionController@show');
    Route::get('transaction/report/status','TransactionController@report');
    Route::get('transaction/report/year','TransactionController@reportByYear');
    Route::get('check','TransactionController@setExpiredTransaction');
    Route::PUT('updateresi/{id}','TransactionController@updateResi');
    Route::resource('role','RoleController');
    Route::resource('permission','PermissionController');
    Route::resource('user','UserController');
    Route::get('profile/{id}/edit','UserController@editProfile');
    Route::get('transaction/invoice/{id}','TransactionController@invoice');
    Route::PUT('profile/{id}','UserController@updateProfile')->name('update.profile');
    Route::get('site/edit','SiteController@edit');
    Route::PUT('site/update','SiteController@update');
    Route::resource('site','SiteController');
    Route::get('transaction_status',function(){
        return View::make('front_end.store.success');
    });
    Route::view('/profile','front_end.store.profile');
    Route::get('dashboard','SiteController@dashboard')->name('dashboard');
    //khusus api
    Route::prefix('api')->group(function(){
        Route::get('cities','CityController@getCities');
        Route::POST('cost','TransactionController@cekOngkir');
        Route::POST('cart/{id}/update','TransactionCOntroller@updateItem');
        Route::delete('cart/{id}/delete','TransactionCOntroller@deleteItem');
        Route::get('carts','TransactionController@getCarts');
        Route::get('categories','CategoryController@getCategories');
        Route::get('sizes','SizeController@getSizes');
        Route::get('provinces','ProvinceController@getProvince');
    });
// });

Route::get('auth/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\LoginController@handleProviderCallback');
Route::get('activate', 'Auth\ActivationController@activate')->name('auth.activate');
// Route::get('/', 'HomeController@index');

Route::get('/about',function () {
    return view('about');
});

Route::get('lookbook', function () {
    $lookbooks = \App\Lookbook::with('detailLookbook')->get();
    return view('lookbook')->with('lookbooks',$lookbooks);
});

Route::get('lookbook/index','LookbookController@index');
Route::get('lookbook/{id}/show', 'LookbookController@show');
Route::get('lookbook/{id}/edit', 'LookbookController@edit');
Route::get('lookbook/create','LookbookController@create')->name('lookbook.create');
Route::post('lookbook','LookbookController@store')->name('lookbook.store');
Route::post('lookbook/{id}','LookbookController@update')->name('lookbook.update');
Route::delete('lookbook/{id}','LookbookController@destroy');
Route::get('send','LookbookController@sendEmail');
Auth::routes(['verify' => true]);

// Route::get('/', 'HomeController@index')->name('home');

Route::POST('notification/handler','TransactionController@notificationHandler');

// Route::get('/', function(){
//     return view('welcome');
// });



resources/views/backend/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pushop</title>
</head>

<link rel="stylesheet" href="{{ asset('css/backend/sb-admin-2.css') }}">
@stack('styles')
<body id="page-top">
<div id="app">
    <!-- Page Wrapper -->
  <div id="wrapper">

<!-- Sidebar -->
@include('backend.layouts.sidebar')
<!-- End of Sidebar -->

<!-- Content Wrapper -->
<div id="content-wrapper" class="d-flex flex-column">

  <!-- Main Content -->
  <div id="content">

    <!-- Topbar -->
   @include('backend.layouts.topbar')
    <!-- End of Topbar -->

    <!-- Begin Page Content -->
    <div class="container-fluid">
    
      @yield('content')

    </div>
    <!-- /.container-fluid -->

  </div>
  <!-- End of Main Content -->

  <!-- Footer -->
  @include('backend.layouts.footer')
  <!-- End of Footer -->

</div>
<!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
<i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
      <button class="close" type="button" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
    <div class="modal-footer">
      <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
      <form action="{{ route('logout') }}" method="post">
      @csrf
      <button type="submit" class="btn btn-primary" href="login.html">Logout</button>
      </form>
    </div>
  </div>
</div>
</div>
</div>
  

  <!-- Bootstrap core JavaScript-->
  <script src="{{ asset('js/app.js') }}"></script>
  <script src="{{ asset('backend/js/sb-admin-2.js') }}"></script>
  
@stack('scripts')
</body>

</html>

resources/views/backend/layouts/footer.blade.php
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
      <div class="copyright text-center my-auto">
        <span>Copyright &copy; Pushop {{ date('Y')}}</span>
      </div>
    </div>
  </footer>

resources/views/backend/layouts/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url('dashboard') }}">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Pushop</div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item">
    <a class="nav-link" href="{{ url('dashboard') }}">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Interface
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
      <i class="fas fa-fw fa-cog"></i>
      <span>Page</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Custom Components:</h6>
        <a class="collapse-item" href="{{ url('lookbook/index') }}">Lookbook</a>
      </div>
    </div>
  </li>

  <!-- Nav Item - Utilities Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
      <i class="fas fa-fw fa-wrench"></i>
      <span>Master</span>
    </a>
    <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Admin</h6>
        @can('user.create')
        <a class="collapse-item" href="{{  url('user') }}">User</a>
        @endcan

        @can('role.create')
        <a class="collapse-item" href="{{  url('role') }}">Role</a>
        @endcan

        @can('permission.create')
        <a class="collapse-item" href="{{  url('permission') }}">Permissions</a>
        @endcan

        <h6 class="collapse-header">Products</h6>

        @can('product.create')
        <a class="collapse-item" href="{{ route('category.index') }}">Kategori</a>
        @endcan

        @can('product.create')
        <a class="collapse-item" href="{{ url('product') }}">Barang</a>
        @endcan
      </div>
    </div>
  </li>

  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTransaksi" aria-expanded="true" aria-controls="collapseTransaksi">
      <i class="fas fa-fw fa-wrench"></i>
      <span>Transaksi</span>
    </a>
    <div id="collapseTransaksi" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
      
        <a class="collapse-item" href="{{ url('transaction') }}">Daftar Transaksi</a>
      </div>
    </div>
  </li>


</ul>

resources/views/backend/layouts/topbar.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

<!-- Sidebar Toggle (Topbar) -->
<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
  <i class="fa fa-bars"></i>
</button>


<!-- Topbar Navbar -->
<ul class="navbar-nav ml-auto">

  <!-- Nav Item - Search Dropdown (Visible Only XS) -->
  <li class="nav-item dropdown no-arrow d-sm-none">
    <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-search fa-fw"></i>
    </a>
    <!-- Dropdown - Messages -->
    <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
      <form class="form-inline mr-auto w-100 navbar-search">
        <div class="input-group">
          <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <button class="btn btn-primary" type="button">
              <i class="fas fa-search fa-sm"></i>
            </button>
          </div>
        </div>
      </form>
    </div>
  </li>

  <!-- Nav Item - Alerts -->
  <li class="nav-item dropdown no-arrow mx-1">
    <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-bell fa-fw"></i>
      <!-- Counter - Alerts -->
      <span class="badge badge-danger badge-counter">{{ $transactions->count() }}</span>
    </a>
    <!-- Dropdown - Alerts -->
    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
      <h6 class="dropdown-header">
        Notifikasi
      </h6>
      @foreach($transactions as $transaction)
      <a class="dropdown-item d-flex align-items-center" href="{{ url('payment/'.$transaction->id) }}">
        <div class="mr-3">
          <div class="icon-circle bg-success">
            <i class="fas fa-donate text-white"></i>
          </div>
        </div>
        <div class="font-weight-bold">
          <div class="small text-gray-500">{{ $transaction->created_at }}</div>
          Transaksi Baru {{ $transaction->invoice }}
        </div>
      </a>
      @endforeach
      <a class="dropdown-item text-center small text-gray-500" href="{{ url('transaction') }}">Lihat Semua Transaksi</a>
    </div>
  </li>
  <div class="topbar-divider d-none d-sm-block"></div>

  <!-- Nav Item - User Information -->
  <li class="nav-item dropdown no-arrow">
    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ auth()->user()->name }}</span>
      <img class="img-profile rounded-circle" src="{{ auth()->user()->image != null ? auth()->user()->image : asset('images/avatar-1.png') }}">
    </a>
    <!-- Dropdown - User Information -->
    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
      <a class="dropdown-item" href="#">
        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
        Profile
      </a>
      <!-- <a class="dropdown-item" href="#">
        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
        Settings
      </a>
      <a class="dropdown-item" href="#">
        <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
        Activity Log
      </a> -->
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
        Logout
      </a>
    </div>
  </li>

</ul>

</nav>
